# Generated by Django 4.1.7 on 2023-04-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Title', models.CharField(max_length=30)),
                ('ShortText', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LandingFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon', models.ImageField(upload_to='')),
                ('Titel', models.CharField(max_length=30)),
                ('SmallText', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LandingGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image1', models.ImageField(upload_to='')),
                ('Image2', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LandingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Introduction', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LandingTestimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testimonials', models.TextField(max_length=200)),
                ('Image', models.ImageField(upload_to='')),
                ('Name', models.CharField(max_length=20)),
                ('Designation', models.CharField(max_length=20)),
            ],
        ),
    ]
